# Generated by Django 5.2.7 on 2025-11-14 03:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Assessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "assessment_type",
                    models.CharField(
                        choices=[
                            ("QUIZ", "Cuestionario Técnico"),
                            ("CODING", "Prueba Práctica de Código"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("EASY", "Fácil"),
                            ("MEDIUM", "Medio"),
                            ("HARD", "Difícil"),
                        ],
                        default="MEDIUM",
                        max_length=10,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "time_limit_minutes",
                    models.IntegerField(
                        default=60, help_text="Tiempo límite en minutos"
                    ),
                ),
                (
                    "passing_score",
                    models.FloatField(
                        default=70.0, help_text="Porcentaje mínimo para aprobar"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pendiente"),
                            ("IN_PROGRESS", "En Progreso"),
                            ("COMPLETED", "Completada"),
                            ("EVALUATED", "Evaluada"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "score",
                    models.FloatField(
                        blank=True, help_text="Puntuación final (0-100)", null=True
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessments",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("MULTIPLE_CHOICE", "Opción Múltiple"),
                            ("TRUE_FALSE", "Verdadero/Falso"),
                            ("CODE", "Código (Editor Monaco)"),
                            ("SHORT_ANSWER", "Respuesta Corta"),
                        ],
                        max_length=20,
                    ),
                ),
                ("question_text", models.TextField(help_text="Texto de la pregunta")),
                (
                    "code_snippet",
                    models.TextField(
                        blank=True, help_text="Código de ejemplo o plantilla inicial"
                    ),
                ),
                (
                    "options",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Array de opciones: ['Opción A', 'Opción B', ...]",
                    ),
                ),
                (
                    "correct_answer",
                    models.TextField(
                        blank=True,
                        help_text="Respuesta correcta o índice de opción correcta",
                    ),
                ),
                (
                    "programming_language",
                    models.CharField(
                        blank=True,
                        help_text="python, javascript, java, etc.",
                        max_length=50,
                    ),
                ),
                (
                    "test_cases",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Casos de prueba para validar código",
                    ),
                ),
                (
                    "points",
                    models.FloatField(
                        default=10.0, help_text="Puntos que vale esta pregunta"
                    ),
                ),
                (
                    "order",
                    models.IntegerField(default=0, help_text="Orden de aparición"),
                ),
                (
                    "explanation",
                    models.TextField(
                        blank=True, help_text="Explicación de la respuesta correcta"
                    ),
                ),
                ("generated_by_ai", models.BooleanField(default=False)),
                (
                    "ai_prompt",
                    models.TextField(
                        blank=True, help_text="Prompt usado para generar la pregunta"
                    ),
                ),
                (
                    "assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="assessments.assessment",
                    ),
                ),
            ],
            options={
                "ordering": ["assessment", "order"],
            },
        ),
        migrations.CreateModel(
            name="CandidateAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "answer_text",
                    models.TextField(
                        blank=True, help_text="Respuesta de texto o código"
                    ),
                ),
                (
                    "selected_option_index",
                    models.IntegerField(
                        blank=True,
                        help_text="Índice de opción seleccionada (para multiple choice)",
                        null=True,
                    ),
                ),
                ("is_correct", models.BooleanField(blank=True, null=True)),
                ("points_earned", models.FloatField(default=0.0)),
                (
                    "feedback",
                    models.TextField(
                        blank=True, help_text="Retroalimentación del evaluador o IA"
                    ),
                ),
                ("answered_at", models.DateTimeField(auto_now_add=True)),
                (
                    "time_spent_seconds",
                    models.IntegerField(
                        default=0, help_text="Tiempo que tomó responder"
                    ),
                ),
                (
                    "code_output",
                    models.TextField(
                        blank=True, help_text="Salida del código ejecutado"
                    ),
                ),
                (
                    "test_results",
                    models.JSONField(
                        blank=True, default=dict, help_text="Resultados de test cases"
                    ),
                ),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidate_answers",
                        to="assessments.question",
                    ),
                ),
            ],
            options={
                "ordering": ["-answered_at"],
            },
        ),
        migrations.AddIndex(
            model_name="assessment",
            index=models.Index(
                fields=["candidate", "status"], name="assessments_candida_f9f150_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="assessment",
            index=models.Index(
                fields=["project"], name="assessments_project_6034ab_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                fields=["assessment", "order"], name="assessments_assessm_815df6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="candidateanswer",
            index=models.Index(
                fields=["candidate", "question"], name="assessments_candida_1b8e95_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="candidateanswer",
            unique_together={("question", "candidate")},
        ),
    ]
