# Generated by Django 5.2.7 on 2026-01-12 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiting', '0002_application_extracted'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='ai_analysis',
            field=models.TextField(blank=True, null=True),
        ),
    ]
